config/routes.rb
WhatsThis::Application.routes.draw do

  root 'games#index' # Home page.  Has all in progress games.
  get '/test' => 'games#test' # Sandbox

  ### GAMES
  post '/games' => 'games#create' # Create a new game in database
  get '/games/completed' => 'games#completed' # View a list of all completed games
  get '/games/new' => 'games#new'

  ### USERS
  get '/users/games' => 'users#games' # User can only see games they've been in, hence no id
  post '/users' => 'users#create' # Sign up.  Use ajax to post to controller.
  post '/users/login' => 'users#login' # User login.  Ajax post creates new session.
  get '/users/logout' => 'users#logout'

  ### ROUNDS
  get '/games/:game_id/rounds/new' => 'rounds#new', as: :rounds_new
  post '/rounds/create_drawing' => 'rounds#create_drawing'
  post '/rounds/create_description' => 'rounds#create_description'

  match '/get_completed_games', to: 'games#get_completed_games', via: 'get'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :rounds

  def is_complete?
    self.rounds.count >= 10 ? true : false
  end

  def check_finished
    self.update_attribute("is_complete", true) if self.is_complete?
  end
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :game
  belongs_to :player, class_name: "User", foreign_key: "user_id"
  validates :content, presence: true
  validates :content_type, presence: true, inclusion: { in: %w(drawing description) }

  def prepared_content
    content = self.content
    if self.content_type == "description"
      content
    elsif self.content_type == "drawing"
      content.gsub!(/width="\d+"/, '')
      content.gsub!(/height="\d+"/, 'preserveAspectRatio="xMinYMin meet" viewBox="0 0 500 500"')
      content.html_safe
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :games
  has_many :rounds, through: :games
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :user_logged_in?

  def current_user
    @current_user ||= session[:user_id]
  end

  def user_logged_in?
    current_user != nil
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def test  
    @round = Round.find(1)
    p @round.prepared_content
  end

  def index
    games = Game.where(is_complete: false)
    @first_game_set = games.shift(3)
    @remaining_game_sets = []
    while games.any?
      @remaining_game_sets << games.shift(3)
    end
  end

  def create
    if user_logged_in?
      game = Game.create(user_id: current_user)
      Round.create( game_id: game.id,
                    user_id: current_user,
                    content: params['round']['content'],
                    content_type: params['round']['content_type'])
    end
    redirect_to root_path
  end

  def new
    if user_logged_in?
      session.delete(:game_id)
    else
      flash[:error] = "Please log in to create a new game!"
      redirect_to root_path
    end
  end

  def completed
  end

  def get_completed_games
    respond_to do |format|
      format.html { render :json => get_completed_games_json }
      format.json { render :json => get_completed_games_json }
    end
  end

  private
  def get_completed_games_json
    @completed_games = Game.where(is_complete: true)
    front_end_games_model = @completed_games.each_with_object [] do |game, g_model|
      round_model = game.rounds.each_with_object [] do |round, r_model|
        r_model << {  id:           round.id,
                      player_id:    round.user_id,
                      content:      round.prepared_content,
                      content_type: round.content_type }
      end

      g_model << {  id:         game.id,
                    creator_id: game.user_id,
                    rounds:     round_model }
    end

    # @game_model_data_json = front_end_games_model.to_json.html_safe
    front_end_games_model
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

  def new #this needs to be refactored
    if user_logged_in?
      @game = Game.find(params[:game_id])
      if @game.rounds.last.user_id == current_user
        flash[:error] = "Dude, you can't play your own contribution. Lame."
        redirect_to root_path
      else
        @last_round = @game.rounds.last
        session[:game_id] = @game.id
        if @last_round.content_type == "drawing"
          render :new_description_to_game
        else
          render :new_drawing_to_game
        end
      end
    else
      flash[:error] = "Please sign in or create an account to play."
      redirect_to root_path
    end
  end

  def create_drawing
    svg = params["svg"]
    if session[:game_id] #This is an addition to an existing game
      game = Game.find(session[:game_id])
      Round.create( game_id: session[:game_id],
                    user_id: current_user,
                    content: svg,
                    content_type: "drawing")
      game.check_finished
      session.delete(:game_id)
    else #This is the first drawing of a new game
      game = Game.create(user_id: current_user)
      round = Round.create( game_id: game.id,
                            user_id: current_user,
                            content: svg,
                            content_type: "drawing")
    end
    redirect_to root_path
  end

  def create_description
    description = params["description"]
    if session[:game_id] #This is an addition to an existing game
      game = Game.find(session[:game_id])
      Round.create( game_id: session[:game_id],
                    user_id: current_user,
                    content: description,
                    content_type: "description")
      game.check_finished
      session.delete(:game_id)

    else #This is the first drawing of a new game
      game = Game.create(user_id: current_user)
      Round.create( game_id: game.id,
                    user_id: current_user,
                    content: description,
                    content_type: "description")
    end
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    new_user = User.new(user_params)
    if new_user.save
      session[:user_id] = new_user.id
      flash[:success] = "Account successfully created. Welcome #{new_user.username}!"
      redirect_to users_games_path
    else
      flash[:error] = "Signup Error"
      redirect_to root_path
    end
  end

  def login
    if user = User.find_by(username: user_params[:username])
      if user.authenticate(user_params[:password])
        session[:user_id] = user.id
        flash[:success] = "Welcome back #{user.username}!"
        redirect_to users_games_path
      else
        flash[:error] = "Invalid password"
        redirect_to root_path
      end
    else
        flash[:error] = "Invalid username"
        redirect_to root_path
    end
  end

  def logout
    session.clear
    redirect_to root_path
  end

  def games
    if user_logged_in?
      @user = User.find(session[:user_id])
      @created_games = @user.games
      @played_rounds = @user.rounds
      render 'games'
    else
      redirect_to root_path
    end
  end



  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
      case level
          when :notice then "alert alert-info"
          when :success then "alert alert-success"
          when :error then "alert alert-error"
          when :alert then "alert alert-error"
      end
  end
  
end

app/views/games/_canvas.html.erb
<div class="canvas-tools-container">
  <div class='brush-width-controller'>
    <span id="brush-width-label">Brush Width:</span>
    <span class="width-option" data-width="5" style="font-weight:100">thin</span>
    <span class="width-option default" data-width="10" style="font-weight:400">regular</span>
    <span class="width-option" data-width="22" style="font-weight:700">thick</span>
    <span class="width-option" data-width="70" style="font-weight:700">MASSIVE</span>
  </div>
  <button class="save-picture-btn btn btn-primary" >Save picture</button>
  <div class="brush-color-controller">
    <ul class="brush-color-controller">
      <li class="color-option default active" style="background-color:black"></li>
      <li class="color-option" style="background-color:white"></li>
      <li class="color-option" style="background-color:gray"></li>
      <li class="color-option" style="background-color:blue"></li>
      <li class="color-option" style="background-color:navy"></li>
      <li class="color-option" style="background-color:purple"></li>
      <li class="color-option" style="background-color:yellow"></li>
      <li class="color-option" style="background-color:orange"></li>
      <li class="color-option" style="background-color:brown"></li>
      <li class="color-option" style="background-color:pink"></li>
      <li class="color-option" style="background-color:green"></li>
    </ul>
  </div>
  <div class="canvas-container">
    <canvas id="canvas" width="400" height="400" class="c"></canvas>
  </div>
</div>

app/views/games/_describe_form.html.erb
<%= form_tag(rounds_create_description_path) do %>
  <div class="form-group">
    <%= label_tag(:description, "Describe the Picture!") %>
    <%= text_area_tag 'description', nil, rows: 5, class: 'form-control' %>
  </div>
  <%= button_tag 'Submit!', class: 'btn btn-primary' %>
<% end %>

app/views/games/_new_game_describe_form.html.erb
<%= form_tag(rounds_create_description_path) do %>
  <div class="form-group">
    <%= label_tag(:description, "Write Something!") %>
    <%= text_area_tag 'description', nil, rows: 5, class: 'form-control' %>
  </div>
  <%= button_tag 'Submit!', class: 'btn btn-primary' %>
<% end %>

app/views/games/completed.html.erb
<div ng-app="app">
  <div ng-controller="CompletedCtrl">

    <div ng-repeat="game in games" class="col-md-3 col-sm-4 col-xs-6" ng-click="setActiveGame(game)">
      <div ng-bind-html="renderHTML(roundWrapper(game.rounds[0].content, game.rounds[0].content_type))">
      </div>
    </div>

    <div class="modal fade modal-game" id="completedGameModal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <div ng-repeat="round in activeGame.rounds" class="frames">
              <div ng-bind-html="renderHTML(roundWrapper(round.content, round.content_type))">
              </div>
            </div> <!-- ng-repeat -->
          </div> <!-- .modal-body -->
        </div> <!-- .modal-content -->
      </div> <!-- .modal-dialog -->
    </div> <!-- .modal -->
  </div> <!-- ng-controller="completedCtrl" -->
</div> <!-- ng-app="completedGames" -->

app/views/games/index.html.erb
<!-- @first_game_set -->
<!-- @remaining_game_sets -->

<div class="container">
  <div class="col-md-12">
   <h1>Active Games</h1>

   <div class="well">
    <div id="myCarousel" class="carousel slide">

      <!-- Carousel items -->
      <div class="carousel-inner">
        <div class="item active">
          <div class="row">

            <% @first_game_set.each do |game| %>
              <div class="col-sm-4">

                <% if game.rounds.last.content_type == "drawing" %>
                  <div class="svg-container">
                    <a href="/games/<%= game.id %>/rounds/new"><%= game.rounds.last.prepared_content %></a>
                  </div>
                <% else %>
                  <div class="description-container">
                    <a href="/games/<%= game.id %>/rounds/new">
                      <div class="description-container-table">
                        <div class="description-container-table-cell">
                          <%= game.rounds.last.prepared_content %>
                        </div>
                      </div>
                    </a>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div><!--/row-->
        </div><!--/item-->

        <% @remaining_game_sets.each do |set| %>
          <div class="item">
            <div class="row">
              <% set.each do |game| %>
                <div class="col-sm-4">


                <% if game.rounds.last.content_type == "drawing" %>
                  <div class="svg-container">
                    <a href="/games/<%= game.id %>/rounds/new"><%= game.rounds.last.prepared_content %></a>
                  </div>
                <% else %>
                  <div class="description-container">
                    <a href="/games/<%= game.id %>/rounds/new">
                      <div class="description-container-table">
                        <div class="description-container-table-cell">
                          <%= game.rounds.last.prepared_content %>
                        </div>
                      </div>
                    </a>
                  </div>
                <% end %>


                </div>
              <% end %>
            </div>
          </div>
        <% end %>


      </div>
      <!--/carousel-inner--> <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>

      <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
    </div>
    <!--/myCarousel-->
  </div>
  <!--/well-->
</div>
</div>

app/views/games/new.html.erb
<div ng-app="app" ng-controller="PanelCtrl as panel">
  <div class="col-md-6 col-md-offset-3">
    <ul class="nav nav-pills">
      <li ng-class="{active:tab === 1}"><a href ng-click="selectTab(1)">Draw!</a></li>
      <li ng-class="{active:tab === 2}"><a href ng-click="selectTab(2)">Write!</a></li>
    </ul>

    <div class="tab-pane" ng-show="isSelected(1)">
      <%= render 'canvas' %>
    </div>
    <div class="tab-pane" ng-show="isSelected(2)">
      <%= render 'new_game_describe_form' %>
    </div>
  </div>
</div>

app/views/games/test.html.erb
<!-- <div class='col-md-4'>
  <div class="svg-container">
    <a href="#"><%= @round.prepared_content %></a>
  </div>
</div> -->

<div class="canvas-container">
  <canvas id="testCanvas" class="c"></canvas>
</div>

<div class="canvas-container">
  <canvas id="testCanvas2" class="c"></canvas>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "What's This?", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_logged_in? %>
          <li><%= link_to "Start New Game", games_new_path %></li>
        <% end %>
        <li><%= link_to "Completed Games", games_completed_path %></li>
        <li><%= link_to "TEST", test_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_logged_in? %>
          <li><%= link_to "Log out", users_logout_path %></li>
        <% else %>
          <li>
            <a href="#"
               data-toggle="modal"
               data-target="#loginModal">Log In</a>
            <%= render 'users/login' %>
          </li>
          <li>
            <a href="#"
               data-toggle="modal"
               data-target="#signupModal">Sign Up</a>
            <%= render 'users/signup' %>
          </li>   
        <% end %>   
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhatsThis</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"%>

  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/rounds/new_description_to_game.html.erb
<div class="col-md-10 col-md-offset-1">
  <h1>NEW DESCRIPTION TO GAME</h1>

  <div class="col-md-5">
    <div class="outer-svg-container">
      <div class="svg-container">
        <%= @last_round.prepared_content %>
        <!-- <p><span>Draw this:</span> "<%= @last_round.content %>"</p> -->
      </div>
    </div>
  </div>

  <div class="col-md-5">
    <%= render "/games/describe_form" %>
  </div>

  <!-- <%= render '/games/canvas' %> -->
</div>

app/views/rounds/new_drawing_to_game.html.erb
<div class="col-md-7 col-md-offset-3">
  <div class="description-container-sm">
    <p><span>Draw this:</span> "<%= @last_round.content %>"</p>
  </div>
  <%= render '/games/canvas' %>
</div>

app/views/users/_login.html.erb
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&#215;</button>
        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>

      <div class="modal-body">
        <%= form_tag users_login_path do %>
          <%= label_tag :username %> <br>
          <%= text_field_tag "user[username]", params[:username], class: 'form-control' %><br>

          <%= label_tag :password %><br>
          <%= password_field_tag "user[password]", params[:password], class: 'form-control' %><br>
          <%= submit_tag(value = "Login", class:'btn btn-primary') %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <% end %>
      </div><!-- /.modal-body -->
    </div> <!-- /.modal-content -->
  </div> <!-- /.modal-dialog -->
</div> <!-- /.modal fade -->

app/views/users/_signup.html.erb
<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&#215;</button>
        <h4 class="modal-title" id="myModalLabel">Create A New Account</h4>
      </div>

      <div class="modal-body">
        <%= form_tag users_path do %>
          <%= label_tag :username %> <br>
          <%= text_field_tag "user[username]", params[:username], class: 'form-control' %><br>

          <%= label_tag :password %> <br>
          <%= password_field_tag "user[password]", params[:passwrd], class: 'form-control' %><br>

          <%= label_tag :password_confirmation %> <br>
          <%= password_field_tag "user[password_confirmation]", params[:password_confirmation], class: 'form-control' %><br>

          <%= submit_tag(value = "Create Account!", class:'btn btn-primary') %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <% end %>
      </div><!-- /.modal-body -->
    </div><!-- /.modal-content -->
  </div> <!-- /.modal-dialog -->
</div> <!-- /.modal fade -->

app/views/users/games.html.erb
<h1>Users' Games</h1>